import type { Media } from "./types";

/**
 * Catalogue de la librairie — ouvrages publiés par les éditions Les 7 Lectures
 * (titres, auteurs, prix, ISBN et couvertures repris de https://les7lectures.com/livres/).
 *
 * Pour ajouter un livre : ajouter un objet (couverture dans /public/images/livres/).
 * `purchaseUrl` pointe vers la fiche de l'ouvrage sur les7lectures.com.
 * `sku` servira à brancher une boutique intégrée plus tard (voir src/lib/commerce.ts).
 */
export interface Book {
  slug: string;
  title: string;
  subtitle: string | null;
  author: string | null;
  description: string | null;
  cover: Media;
  /** Prix tel qu'affiché par l'éditeur (ex. « 12,00 € (papier) & 8,00 € (ebook) »). */
  priceLabel: string | null;
  isbn: string | null;
  purchaseUrl: string | null;
  sku?: string | null;
}

export const books: Book[] = [
  {
    slug: "moulay-al-hassan-al-karkari",
    title: "Moulay al-Hassan al-Karkari",
    subtitle: "Biographie d’un maître soufi",
    author: "Mohamed Ouhraich",
    description: "Il existe des awliyas qui ont vécu dans l’occultation plutôt que l’apparition, le silence plutôt que la renommée, l’intimité avec Allah plutôt que la reconnaissance des créatures. Le Shaykh Moulay al-Hassan al-Karkari al-Idrissi fut de ceux-là.",
    cover: { src: "/images/livres/moulay-al-hassan-al-karkari.jpg", alt: "Couverture — Moulay al-Hassan al-Karkari", width: 600, height: 950 },
    priceLabel: "11,00 € (papier) & 7,00 € (ebook)",
    isbn: "978-2-931274-25-5",
    purchaseUrl: "https://les7lectures.com/moulay-al-hassan-al-karkari/",
  },
  {
    slug: "al-karkari",
    title: "Al-Karkari",
    subtitle: "Origines et Histoire d’une lignée Chérifienne",
    author: "Mohamed Ouhraich",
    description: "Origines et Histoire d’une lignée Chérifienne",
    cover: { src: "/images/livres/al-karkari.jpg", alt: "Couverture — Al-Karkari", width: 600, height: 956 },
    priceLabel: "16,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-931274-23-1",
    purchaseUrl: "https://les7lectures.com/al-karkari/",
  },
  {
    slug: "croire-ou-ne-pas-croire-en-dieu",
    title: "Croire ou ne pas croire en Dieu",
    subtitle: "Réponse inspirée des enseignements du Cheikh Mohamed Faouzi al-Karkari",
    author: "Fathi Mazni",
    description: "Réponse inspiré des enseignements du Cheikh Mohamed Faouzi al-Karkari",
    cover: { src: "/images/livres/croire-ou-ne-pas-croire-en-dieu.jpg", alt: "Couverture — Croire ou ne pas croire en Dieu", width: 600, height: 950 },
    priceLabel: "10,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-931274-21-7",
    purchaseUrl: "https://les7lectures.com/croire-ou-ne-pas-croire-en-dieu/",
  },
  {
    slug: "les-ascensions-lumineuses",
    title: "Les Ascensions Lumineuses",
    subtitle: "Dhikr de la Karkariya",
    author: "Mohamed Faouzi Al Karkari",
    description: "Cher aimant et aspirant, viens à nous afin que nous puissions étancher ta soif avec le vin de l’amour, dans les coupes des lumières muhammadienne...",
    cover: { src: "/images/livres/les-ascensions-lumineuses.jpg", alt: "Couverture — Les Ascensions Lumineuses", width: 600, height: 851 },
    priceLabel: "15,00 €",
    isbn: "978-2-931274-19-4",
    purchaseUrl: "https://les7lectures.com/les-ascensions-lumineuses/",
  },
  {
    slug: "lecture-du-lam-al-qabd-par-le-ha-tome-3",
    title: "Lecture du Lâm al-Qabd par le Hâ (Tome 3)",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Tome 3 de la Lecture du Lâm al-Qabd par le Hâ. Cours du Shaykh Mohamed Faouzi al-Karkari retranscrit et traduit en français.",
    cover: { src: "/images/livres/lecture-du-lam-al-qabd-par-le-ha-tome-3.jpg", alt: "Couverture — Lecture du Lâm al-Qabd par le Hâ (Tome 3)", width: 600, height: 851 },
    priceLabel: "19,00 € (papier) & 10,00 € (ebook)",
    isbn: "978-2-931274-13-2",
    purchaseUrl: "https://les7lectures.com/lecture-du-lam-al-qabd-par-le-ha-tome-3/",
  },
  {
    slug: "al-servicio-del-destino",
    title: "Al Servicio Del Destino",
    subtitle: "Biografía del Shaykh Mohamed Faouzi al-Karkari",
    author: "Jamil Zaghdoudi",
    description: "Biografía del Shaykh Mohamed Faouzi al-Karkari",
    cover: { src: "/images/livres/al-servicio-del-destino.jpg", alt: "Couverture — Al Servicio Del Destino", width: 600, height: 950 },
    priceLabel: "10,00 € (papier) & 7,00 € (ebook)",
    isbn: "978-2-931274-10-1",
    purchaseUrl: "https://les7lectures.com/al-servicio-del-destino/",
  },
  {
    slug: "des-abysses-du-confinement-a-la-lumiere-de-laccomplissement",
    title: "Des Abysses du Confinement à la Lumière de l’Accomplissement",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Sache que tant que tu parcours cette dūnia, tu es semblable à un nageur suivant une orbite...",
    cover: { src: "/images/livres/des-abysses-du-confinement-a-la-lumiere-de-laccomplissement.jpg", alt: "Couverture — Des Abysses du Confinement à la Lumière de l’Accomplissement", width: 600, height: 956 },
    priceLabel: "15,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-931274-06-4",
    purchaseUrl: "https://les7lectures.com/des-abysses-du-confinement-a-la-lumiere-de-laccomplissement/",
  },
  {
    slug: "les-signes",
    title: "Les Signes",
    subtitle: null,
    author: "Yannis Talla",
    description: "Et si la place qu’on t’avait donnée dans cette existence était bien plus grande que tout ce que tu avais pu imaginer ?",
    cover: { src: "/images/livres/les-signes.jpg", alt: "Couverture — Les Signes", width: 600, height: 956 },
    priceLabel: "14,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-931274-07-1",
    purchaseUrl: "https://les7lectures.com/les-signes/",
  },
  {
    slug: "les-prodiges-du-wali",
    title: "Les Prodiges du Wali",
    subtitle: "Les extraordinaires témoignages des disciples karkaris",
    author: "Mohamed Ouhraich",
    description: "Les extraordinaires témoignages des disciples karkaris",
    cover: { src: "/images/livres/les-prodiges-du-wali.jpg", alt: "Couverture — Les Prodiges du Wali", width: 600, height: 956 },
    priceLabel: "14,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-931274-04-0",
    purchaseUrl: "https://les7lectures.com/les-prodiges-du-wali/",
  },
  {
    slug: "illumination-universelle-theorie-unifiee-de-la-lumiere",
    title: "Illumination Universelle : Théorie unifiée de la lumière",
    subtitle: null,
    author: "Billel Helali",
    description: "Préparez-vous à un voyage extraordinaire au cœur de la lumière, où science et spiritualité se rencontrent dans une danse cosmique éblouissante...",
    cover: { src: "/images/livres/illumination-universelle-theorie-unifiee-de-la-lumiere.jpg", alt: "Couverture — Illumination Universelle : Théorie unifiée de la lumière", width: 600, height: 956 },
    priceLabel: "12,00 € (papier) & 8,00 € (ebook)",
    isbn: "978-2-931274-02-6",
    purchaseUrl: "https://les7lectures.com/illumination-universelle-theorie-unifiee-de-la-lumiere/",
  },
  {
    slug: "peregrinations-du-coeur",
    title: "Pérégrinations du Cœur",
    subtitle: "Siyahat al-Qalb",
    author: "Ibtissem Omrane",
    description: "Tout commence par cette Lumière qui t’éclaire. Elle entre dans la nuit de ta vie comme un soleil qui ne se couche jamais.",
    cover: { src: "/images/livres/peregrinations-du-coeur.jpg", alt: "Couverture — Pérégrinations du Cœur", width: 600, height: 956 },
    priceLabel: "12,00 € (papier) & 8,00 € (ebook)",
    isbn: "978-2-930978-99-4",
    purchaseUrl: "https://les7lectures.com/peregrinations-du-coeur/",
  },
  {
    slug: "les-sentiers-de-la-foi-a-la-lumiere-du-wird",
    title: "Les Sentiers de la Foi à la lumière du Wird",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Al-ma’rifa, ce n’est pas d’avoir des ouvertures pour voir dans d’autres mondes...",
    cover: { src: "/images/livres/les-sentiers-de-la-foi-a-la-lumiere-du-wird.jpg", alt: "Couverture — Les Sentiers de la Foi à la lumière du Wird", width: 600, height: 944 },
    priceLabel: "9,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-930978-98-7",
    purchaseUrl: "https://les7lectures.com/les-sentiers-de-la-foi-a-la-lumiere-du-wird/",
  },
  {
    slug: "ne-frequente-pas-les-disciples",
    title: "Ne fréquente pas les disciples !",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Les disciples sont les maîtres, les seigneurs et les princes !",
    cover: { src: "/images/livres/ne-frequente-pas-les-disciples.jpg", alt: "Couverture — Ne fréquente pas les disciples !", width: 600, height: 946 },
    priceLabel: "9,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-930978-97-0",
    purchaseUrl: "https://les7lectures.com/ne-frequente-pas-les-disciples/",
  },
  {
    slug: "lecture-du-lam-al-qabd-par-le-ha-tome-2",
    title: "Lecture du Lâm al-Qabd par le Hâ (Tome 2)",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Tome 2 de la Lecture du Lâm al-Qabd par le Hâ. Cours du Shaykh Mohamed Faouzi al-Karkari retranscrit et traduit en français.",
    cover: { src: "/images/livres/lecture-du-lam-al-qabd-par-le-ha-tome-2.jpg", alt: "Couverture — Lecture du Lâm al-Qabd par le Hâ (Tome 2)", width: 600, height: 851 },
    priceLabel: "19,00 € (papier) & 10,00 € (ebook)",
    isbn: "978-2-930978-96-3",
    purchaseUrl: "https://les7lectures.com/lecture-du-lam-al-qabd-par-le-ha-tome-2/",
  },
  {
    slug: "recherche-lheritier-du-prophete",
    title: "Recherche l’héritier du Prophète",
    subtitle: null,
    author: "Mohamed Ouhraich",
    description: null,
    cover: { src: "/images/livres/recherche-lheritier-du-prophete.jpg", alt: "Couverture — Recherche l’héritier du Prophète", width: 600, height: 950 },
    priceLabel: "9,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-930978-90-1",
    purchaseUrl: "https://les7lectures.com/recherche-lheritier-du-prophete/",
  },
  {
    slug: "zamzam-del-conocimiento",
    title: "Zamzam del Conocimiento",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Para entender cómo el Sheij guía al discípulo a través de su cuerpo, es necesario saber que todos...",
    cover: { src: "/images/livres/zamzam-del-conocimiento.jpg", alt: "Couverture — Zamzam del Conocimiento", width: 600, height: 956 },
    priceLabel: "15,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-930978-93-2",
    purchaseUrl: "https://les7lectures.com/zamzam-del-conocimiento/",
  },
  {
    slug: "libere-toi-des-apparences-reviens-a-lessentiel",
    title: "Libère-toi des apparences, reviens à l’essentiel",
    subtitle: "Paroles d'Or",
    author: "Mohamed Faouzi Al Karkari",
    description: "L’illusion influe sur l’illusion. Cette illusion que tu as dans la nâsiya t’influence. Dans la nâsiya, tu as la synthèse de toutes les illusions...",
    cover: { src: "/images/livres/libere-toi-des-apparences-reviens-a-lessentiel.jpg", alt: "Couverture — Libère-toi des apparences, reviens à l’essentiel", width: 600, height: 946 },
    priceLabel: "9,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-930978-91-8",
    purchaseUrl: "https://les7lectures.com/libere-toi-des-apparences-reviens-a-lessentiel/",
  },
  {
    slug: "un-regard-sur-la-noble-descendance",
    title: "Un regard sur la noble descendance",
    subtitle: "Paroles d'Or",
    author: "Mohamed Faouzi Al Karkari",
    description: "Pourquoi la sunna doit-elle être revivifiée ? — La wilaya du Prophète est supérieure à sa risala — Qu'as-tu vraiment compris de la chari'a ?...",
    cover: { src: "/images/livres/un-regard-sur-la-noble-descendance.jpg", alt: "Couverture — Un regard sur la noble descendance", width: 600, height: 944 },
    priceLabel: "9,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-930978-89-5",
    purchaseUrl: "https://les7lectures.com/un-regard-sur-la-noble-descendance/",
  },
  {
    slug: "qui-es-tu-pour-le-connaitre",
    title: "Qui es-tu pour Le connaître ?",
    subtitle: "Paroles d'Or",
    author: "Mohamed Faouzi Al Karkari",
    description: "Sois là où Allâh a voulu que tu sois ! Renouveler sa bay’a à chaque wird. Tu ne dois pas prévoir de vivre plus de 63 ans. Vivre le Secret à chaque instant.",
    cover: { src: "/images/livres/qui-es-tu-pour-le-connaitre.jpg", alt: "Couverture — Qui es-tu pour Le connaître ?", width: 600, height: 946 },
    priceLabel: "7€ (papier) & 4€ (ebook)",
    isbn: "978-2-930978-88-8",
    purchaseUrl: "https://les7lectures.com/qui-es-tu-pour-le-connaitre/",
  },
  {
    slug: "connaitre-allah-ton-unique-raison-detre",
    title: "Connaître Allah : ton unique raison d’être",
    subtitle: "Paroles d'Or",
    author: "Mohamed Faouzi Al Karkari",
    description: "Tout cela, ce n’est pas moi qui le dit, alors épargne-moi ta haine, tout autant que ton amour d’ailleurs...",
    cover: { src: "/images/livres/connaitre-allah-ton-unique-raison-detre.jpg", alt: "Couverture — Connaître Allah : ton unique raison d’être", width: 600, height: 944 },
    priceLabel: "7€ (papier) & 4€ (ebook)",
    isbn: "978-2-930978-87-1",
    purchaseUrl: "https://les7lectures.com/connaitre-allah-ton-unique-raison-detre/",
  },
  {
    slug: "zamzam-de-la-connaissance",
    title: "Zamzam de la connaissance",
    subtitle: "Conseils du Shaykh Mohamed Faouzi Al Karkari aux cheminants",
    author: "Mohamed Faouzi Al Karkari",
    description: "Conseils du Shaykh Mohamed Faouzi Al Karkari aux cheminants",
    cover: { src: "/images/livres/zamzam-de-la-connaissance.jpg", alt: "Couverture — Zamzam de la connaissance", width: 600, height: 956 },
    priceLabel: "15,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-930978-85-7",
    purchaseUrl: "https://les7lectures.com/zamzam-de-la-connaissance/",
  },
  {
    slug: "les-convenances-du-compagnonnage-3",
    title: "Les convenances du compagnonnage (3)",
    subtitle: "Tome 3 • Chapitres 49 à 72",
    author: "Mohamed Faouzi Al Karkari",
    description: "Le adab est une obligation et un fondement dans la Voie. C’est par les convenances que l’on construit et établit les états spirituels...",
    cover: { src: "/images/livres/les-convenances-du-compagnonnage-3.jpg", alt: "Couverture — Les convenances du compagnonnage (3)", width: 600, height: 956 },
    priceLabel: "14,00 € (papier) & 8,00 € (ebook)",
    isbn: "978-2-930978-86-4",
    purchaseUrl: "https://les7lectures.com/les-convenances-du-compagnonnage-3/",
  },
  {
    slug: "le-vetement-rapiece",
    title: "Le Vêtement Rapiécé",
    subtitle: "Explications d’un habit prophétique",
    author: "Mohamed Ouhraich",
    description: "Parmi ces fondements, on trouve celui du vêtement rapiécé (muraqa’a) sur lequel nous allons nous pencher dans cet ouvrage...",
    cover: { src: "/images/livres/le-vetement-rapiece.jpg", alt: "Couverture — Le Vêtement Rapiécé", width: 600, height: 950 },
    priceLabel: "9,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-930978-81-9",
    purchaseUrl: "https://les7lectures.com/le-vetement-rapiece/",
  },
  {
    slug: "la-voie-blanche-souple",
    title: "La Voie Blanche (souple)",
    subtitle: "al-Mahajjat al-Bayda",
    author: "Mohamed Faouzi Al Karkari",
    description: "Le Seigneur ﷻ a certes établi pour nous la Voie menant à Lui, claire et évidente pour tous...",
    cover: { src: "/images/livres/la-voie-blanche-souple.jpg", alt: "Couverture — La Voie Blanche (souple)", width: 600, height: 851 },
    priceLabel: "19,00 €",
    isbn: "978-2-930978-80-2",
    purchaseUrl: "https://les7lectures.com/la-voie-blanche-souple/",
  },
  {
    slug: "le-cheminement-spirituel-par-la-lumiere-du-prophete",
    title: "Le Cheminement Spirituel par la Lumière du Prophète",
    subtitle: null,
    author: "Mohamed Ouhraich",
    description: "Le cheminement spirituel est l’objet de beaucoup de fantasmes et de mensonges qui ont...",
    cover: { src: "/images/livres/le-cheminement-spirituel-par-la-lumiere-du-prophete.jpg", alt: "Couverture — Le Cheminement Spirituel par la Lumière du Prophète", width: 600, height: 851 },
    priceLabel: "19,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-930978-79-6",
    purchaseUrl: "https://les7lectures.com/le-cheminement-spirituel-par-la-lumiere-du-prophete/",
  },
  {
    slug: "de-fundamenten-van-de-tariqa-karkariya",
    title: "De fundamenten van de Tariqa Karkariya",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "De Fundamenten van de Karkariya Orde verwoorden de zeven fundamentele principes van het Spirituele Pad zoals vastgelegd in de heilige Koran...",
    cover: { src: "/images/livres/de-fundamenten-van-de-tariqa-karkariya.jpg", alt: "Couverture — De fundamenten van de Tariqa Karkariya", width: 600, height: 893 },
    priceLabel: "16,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-930978-71-0",
    purchaseUrl: "https://les7lectures.com/de-fundamenten-van-de-tariqa-karkariya/",
  },
  {
    slug: "latteinte-du-faite-dans-laffirmation-de-la-vision-a-letat-deveil-des-anges-et-des-prophetes",
    title: "L’atteinte du faîte dans l’affirmation de la vision à l’état d’éveil des anges et des prophètes",
    subtitle: null,
    author: "Abou Nour Muhammad",
    description: "« Qui m’a vu en rêve me verra à l’état d’éveil. » L’auteur entend rapporter la position des savants sunnites sur la compréhension de cette parole prophétique.",
    cover: { src: "/images/livres/latteinte-du-faite-dans-laffirmation-de-la-vision-a-letat-deveil-des-anges-et-des-prophetes.jpg", alt: "Couverture — L’atteinte du faîte dans l’affirmation de la vision à l’état d’éveil des anges et des prophètes", width: 600, height: 950 },
    priceLabel: "10,00 € (papier) & 8,00 € (ebook)",
    isbn: "978-2-930978-68-0",
    purchaseUrl: "https://les7lectures.com/latteinte-du-faite-dans-laffirmation-de-la-vision-a-letat-deveil-des-anges-et-des-prophetes/",
  },
  {
    slug: "la-certitude-du-croyant",
    title: "La certitude du croyant",
    subtitle: "Suivi de La croyance concise",
    author: "Abou Nour Muhammad",
    description: "Les deux ouvrages traduits dans le présent livre figurent parmi les écrits les plus célèbres du Shaykh Muhammad ibn Yusuf al-Sannussiy.",
    cover: { src: "/images/livres/la-certitude-du-croyant.jpg", alt: "Couverture — La certitude du croyant", width: 600, height: 950 },
    priceLabel: "8,00 € (papier) & 5,00 € (ebook)",
    isbn: "978-2-930978-67-3",
    purchaseUrl: "https://les7lectures.com/la-certitude-du-croyant/",
  },
  {
    slug: "recueil-des-receptacles-des-ames",
    title: "Recueil des réceptacles des âmes",
    subtitle: "Poésie contemporaine soufie",
    author: "Mohamed Faouzi Al Karkari",
    description: "Poésie contemporaine soufie",
    cover: { src: "/images/livres/recueil-des-receptacles-des-ames.jpg", alt: "Couverture — Recueil des réceptacles des âmes", width: 600, height: 980 },
    priceLabel: "12,00 €",
    isbn: "978-2-930978-66-6",
    purchaseUrl: "https://les7lectures.com/recueil-des-receptacles-des-ames/",
  },
  {
    slug: "le-soufisme-devoile-tome-1",
    title: "Le Soufisme dévoilé (Tome 1)",
    subtitle: "Réponses à tous les mensonges sur le soufisme",
    author: "Louis Mazué",
    description: "Cet ouvrage intitulé Le Soufisme dévoilé est le premier tome d’un ensemble de trois livres qui traiteront de la question du tassawuf selon trois dimensions...",
    cover: { src: "/images/livres/le-soufisme-devoile-tome-1.jpg", alt: "Couverture — Le Soufisme dévoilé (Tome 1)", width: 600, height: 901 },
    priceLabel: "19,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-930978-76-5",
    purchaseUrl: "https://les7lectures.com/le-soufisme-devoile-tome-1/",
  },
  {
    slug: "lecture-du-lam-al-qabd-par-le-ha-tome-1",
    title: "Lecture du Lâm al-Qabd par le Hâ (Tome 1)",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Exaltée soit la transcendance de Celui qui te créa en Se faisant apparaître Lui-même, de toi-même en toi-même et pour toi-même, façonnant à travers toi...",
    cover: { src: "/images/livres/lecture-du-lam-al-qabd-par-le-ha-tome-1.jpg", alt: "Couverture — Lecture du Lâm al-Qabd par le Hâ (Tome 1)", width: 600, height: 900 },
    priceLabel: "19,00 € (papier) & 9,99 € (ebook)",
    isbn: "978-2-930978-60-4",
    purchaseUrl: "https://les7lectures.com/lecture-du-lam-al-qabd-par-le-ha-tome-1/",
  },
  {
    slug: "les-convenances-du-compagnonnage-2",
    title: "Les convenances du compagnonnage (2)",
    subtitle: "Tome 2 • Chapitres 25 à 48",
    author: "Mohamed Faouzi Al Karkari",
    description: "Le adab est une obligation et un fondement dans la Voie.",
    cover: { src: "/images/livres/les-convenances-du-compagnonnage-2.jpg", alt: "Couverture — Les convenances du compagnonnage (2)", width: 600, height: 956 },
    priceLabel: "14,00 € (papier) & 8,00 € (ebook)",
    isbn: "978-2-930978-74-1",
    purchaseUrl: "https://les7lectures.com/les-convenances-du-compagnonnage-2/",
  },
  {
    slug: "les-voies-dascension-lumineuses",
    title: "Les Voies d’Ascension Lumineuses",
    subtitle: "Invocations de la Tariqa Karkariya",
    author: "Mohamed Faouzi Al Karkari",
    description: "Ton dhikr doit être un dhikr par la langue, par le cœur, par la pensée et la vogue en l’Essence divine.",
    cover: { src: "/images/livres/les-voies-dascension-lumineuses.jpg", alt: "Couverture — Les Voies d’Ascension Lumineuses", width: 600, height: 851 },
    priceLabel: "10,00 €",
    isbn: "978-2-930978-75-8",
    purchaseUrl: "https://les7lectures.com/les-voies-dascension-lumineuses/",
  },
  {
    slug: "le-paradoxe-du-destin-et-du-libre-arbitre-en-islam",
    title: "Le paradoxe du destin et du libre arbitre en Islam",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Quelle place le musulman doit-il accorder au libre arbitre ?",
    cover: { src: "/images/livres/le-paradoxe-du-destin-et-du-libre-arbitre-en-islam.jpg", alt: "Couverture — Le paradoxe du destin et du libre arbitre en Islam", width: 600, height: 990 },
    priceLabel: "6,00 € (papier) – 4,00 € (ebook)",
    isbn: "978-2-930978-69-7",
    purchaseUrl: "https://les7lectures.com/le-paradoxe-du-destin-et-du-libre-arbitre-en-islam/",
  },
  {
    slug: "lappel-de-lesprit",
    title: "L’Appel de l’Esprit",
    subtitle: "Une initiation entre Ciel & Terre",
    author: "Sébastien Biraud",
    description: "Une initiation entre Ciel & Terre",
    cover: { src: "/images/livres/lappel-de-lesprit.jpg", alt: "Couverture — L’Appel de l’Esprit", width: 600, height: 950 },
    priceLabel: "10,00 € (papier) – 7,00 € (ebook)",
    isbn: "978-2-930978-70-3",
    purchaseUrl: "https://les7lectures.com/lappel-de-lesprit/",
  },
  {
    slug: "insegnamento-contemporaneo-sufi",
    title: "Insegnamento Contemporaneo Sufi",
    subtitle: "I Fondamenti della via Karkariya",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/insegnamento-contemporaneo-sufi.jpg", alt: "Couverture — Insegnamento Contemporaneo Sufi", width: 600, height: 980 },
    priceLabel: "11,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-930978-49-9",
    purchaseUrl: "https://les7lectures.com/insegnamento-contemporaneo-sufi/",
  },
  {
    slug: "si-tu-ne-le-vois-pas-lui-te-voit",
    title: "Si tu ne Le vois pas, Lui te voit",
    subtitle: "Sept passages du Coran traitant des pièges de la nafs",
    author: "Mohamed Ouhraich",
    description: "À travers sept nouveaux passages coraniques, nous allons chercher à identifier les pièges de la nafs...",
    cover: { src: "/images/livres/si-tu-ne-le-vois-pas-lui-te-voit.jpg", alt: "Couverture — Si tu ne Le vois pas, Lui te voit", width: 600, height: 980 },
    priceLabel: "9,00 € (papier) & 6,00 € (ebook)",
    isbn: "978-2-930978-48-2",
    purchaseUrl: "https://les7lectures.com/si-tu-ne-le-vois-pas-lui-te-voit/",
  },
  {
    slug: "los-fundamentos-de-la-tariqa-karkariya",
    title: "Los Fundamentos de la Tariqa Karkariya",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/los-fundamentos-de-la-tariqa-karkariya.jpg", alt: "Couverture — Los Fundamentos de la Tariqa Karkariya", width: 600, height: 980 },
    priceLabel: "14,00 € (papel) & 9,99 € (ebook)",
    isbn: "978-2-930978-43-7",
    purchaseUrl: "https://les7lectures.com/los-fundamentos-de-la-tariqa-karkariya/",
  },
  {
    slug: "introduction-au-lam-al-qabd",
    title: "Introduction au lâm al-qabd",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Tu deviens ainsi donc lillâh… c’est-à-dire qu’Il saisit ta nafs, ton corps, ta forme, ton image, ton esprit…",
    cover: { src: "/images/livres/introduction-au-lam-al-qabd.jpg", alt: "Couverture — Introduction au lâm al-qabd", width: 600, height: 900 },
    priceLabel: "14,00 € (papier) & 10,00 € (ebook)",
    isbn: "978-2-930978-77-2",
    purchaseUrl: "https://les7lectures.com/introduction-au-lam-al-qabd/",
  },
  {
    slug: "epitre-lunaire",
    title: "Épître Lunaire",
    subtitle: "Conseils aux cheminants",
    author: "Mohamed Faouzi Al Karkari",
    description: "Conseils du Shaykh Mohamed Faouzi Al Karkari aux cheminants",
    cover: { src: "/images/livres/epitre-lunaire.jpg", alt: "Couverture — Épître Lunaire", width: 600, height: 980 },
    priceLabel: "12,00 € (papier) & 8,00 € (ebook)",
    isbn: "978-2-930978-38-3",
    purchaseUrl: "https://les7lectures.com/epitre-lunaire/",
  },
  {
    slug: "les-convenances-du-compagnonnage",
    title: "Les convenances du compagnonnage (1)",
    subtitle: null,
    author: "Mohamed Faouzi Al Karkari",
    description: "Le adab est une obligation et un fondement dans la Voie.",
    cover: { src: "/images/livres/les-convenances-du-compagnonnage.jpg", alt: "Couverture — Les convenances du compagnonnage (1)", width: 600, height: 980 },
    priceLabel: "10,00 € (papier) & 5,00 € (ebook)",
    isbn: "978-2-9309787-34",
    purchaseUrl: "https://les7lectures.com/les-convenances-du-compagnonnage/",
  },
  {
    slug: "le-livre-du-secret",
    title: "Le Livre du Secret",
    subtitle: "Syllabaire initiatique",
    author: "Mohamed Faouzi Al Karkari",
    description: "Syllabaire initiatique",
    cover: { src: "/images/livres/le-livre-du-secret.jpg", alt: "Couverture — Le Livre du Secret", width: 600, height: 980 },
    priceLabel: "19,00 € (papier) – 9,99 € (ebook)",
    isbn: "978-2-930978-45-1",
    purchaseUrl: "https://les7lectures.com/le-livre-du-secret/",
  },
  {
    slug: "de-toi-a-lui",
    title: "De Toi à Lui",
    subtitle: "La Voie d'ascension du musulman",
    author: "Louis Mazué",
    description: "La Voie d'ascension du musulman...",
    cover: { src: "/images/livres/de-toi-a-lui.jpg", alt: "Couverture — De Toi à Lui", width: 600, height: 980 },
    priceLabel: "6,00 € (papier) & 3,00 € (ebook)",
    isbn: "978-2-930978-44-4",
    purchaseUrl: "https://les7lectures.com/de-toi-a-lui/",
  },
  {
    slug: "les-secrets-derriere-le-voile",
    title: "Les Secrets derrière le Voile",
    subtitle: "Une lecture des versets de la Bible par un soufi anciennement chrétien",
    author: "Pierre-Antoine Segri",
    description: null,
    cover: { src: "/images/livres/les-secrets-derriere-le-voile.jpg", alt: "Couverture — Les Secrets derrière le Voile", width: 600, height: 980 },
    priceLabel: "12,00 € (papier) & 8,00 € (ebook)",
    isbn: "978-2-930978-42-0",
    purchaseUrl: "https://les7lectures.com/les-secrets-derriere-le-voile/",
  },
  {
    slug: "le-pelerinage-une-initiation-soufie",
    title: "Le pèlerinage : une initiation soufie",
    subtitle: "Une ‘umrah sur les pas du Walî",
    author: "Mohamed Ouhraich",
    description: null,
    cover: { src: "/images/livres/le-pelerinage-une-initiation-soufie.jpg", alt: "Couverture — Le pèlerinage : une initiation soufie", width: 600, height: 980 },
    priceLabel: "19,00 €",
    isbn: "978-2-930978-41-3",
    purchaseUrl: "https://les7lectures.com/le-pelerinage-une-initiation-soufie/",
  },
  {
    slug: "comme-si-tu-le-voyais",
    title: "Comme si tu Le voyais",
    subtitle: "Sept points du cheminement spirituel dans le Coran",
    author: "Mohamed Ouhraich",
    description: null,
    cover: { src: "/images/livres/comme-si-tu-le-voyais.jpg", alt: "Couverture — Comme si tu Le voyais", width: 600, height: 980 },
    priceLabel: "8,00 € (papier) & 5,00 € (ebook)",
    isbn: "978-2-930978-37-6",
    purchaseUrl: "https://les7lectures.com/comme-si-tu-le-voyais/",
  },
  {
    slug: "les-fruits-du-suivi",
    title: "Les Fruits du Suivi",
    subtitle: "Sur les pas du Prophète",
    author: "Louis Mazué",
    description: null,
    cover: { src: "/images/livres/les-fruits-du-suivi.jpg", alt: "Couverture — Les Fruits du Suivi", width: 600, height: 980 },
    priceLabel: "11,00 € (papier) & 8,00 € (ebook)",
    isbn: "978-2-930978-39-0",
    purchaseUrl: "https://les7lectures.com/les-fruits-du-suivi/",
  },
  {
    slug: "la-lumiere-selon-les-maitres-soufis",
    title: "La Lumière selon les maîtres soufis",
    subtitle: "La Voie Blanche - Chapitre IV",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/la-lumiere-selon-les-maitres-soufis.jpg", alt: "Couverture — La Lumière selon les maîtres soufis", width: 600, height: 980 },
    priceLabel: "7,00 € (papier) & 4,00 € (ebook)",
    isbn: "978-2-930978-33-8",
    purchaseUrl: "https://les7lectures.com/la-lumiere-selon-les-maitres-soufis/",
  },
  {
    slug: "avant-propos-des-lumieres",
    title: "Avant-propos des Lumières",
    subtitle: "La Voie Blanche - Chapitre I",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/avant-propos-des-lumieres.jpg", alt: "Couverture — Avant-propos des Lumières", width: 600, height: 980 },
    priceLabel: "7,00 € (papier) & 4,00 € (ebook)",
    isbn: "978-2-930978-34-5",
    purchaseUrl: "https://les7lectures.com/avant-propos-des-lumieres/",
  },
  {
    slug: "reflet-des-sagesses-lumineuses",
    title: "Reflet des sagesses lumineuses",
    subtitle: "Commentaire ésotérique",
    author: "Mehdi Badeche",
    description: null,
    cover: { src: "/images/livres/reflet-des-sagesses-lumineuses.jpg", alt: "Couverture — Reflet des sagesses lumineuses", width: 600, height: 980 },
    priceLabel: "4,00 €",
    isbn: "978-2-930978-31-4",
    purchaseUrl: "https://les7lectures.com/reflet-des-sagesses-lumineuses/",
  },
  {
    slug: "au-service-du-destin",
    title: "Au service du destin",
    subtitle: "Biographie du Shaykh Mohamed Faouzi Al Karkari",
    author: "Jamil Zaghdoudi",
    description: null,
    cover: { src: "/images/livres/au-service-du-destin.jpg", alt: "Couverture — Au service du destin", width: 600, height: 980 },
    priceLabel: "10,00 € (papier) & 5,00 € (ebook)",
    isbn: "978-2-930978-21-5",
    purchaseUrl: "https://les7lectures.com/au-service-du-destin/",
  },
  {
    slug: "les-fondements-de-la-tariqa-karkariya",
    title: "Les fondements de la Tariqa Karkariya",
    subtitle: "Fondement de la voie soufie Karkariya",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/les-fondements-de-la-tariqa-karkariya.jpg", alt: "Couverture — Les fondements de la Tariqa Karkariya", width: 600, height: 980 },
    priceLabel: "16,00 € (papier) – 9,99 € (ebook)",
    isbn: "978-2-930978-23-9",
    purchaseUrl: "https://les7lectures.com/les-fondements-de-la-tariqa-karkariya/",
  },
  {
    slug: "un-regard-sur-mon-ame",
    title: "Un regard sur mon âme",
    subtitle: "Recueil de poèmes et sagesses",
    author: "Florian Eme",
    description: null,
    cover: { src: "/images/livres/un-regard-sur-mon-ame.jpg", alt: "Couverture — Un regard sur mon âme", width: 600, height: 980 },
    priceLabel: "9,00 €",
    isbn: "978-2-930978-19-2",
    purchaseUrl: "https://les7lectures.com/un-regard-sur-mon-ame/",
  },
  {
    slug: "par-letoile-lorsquelle-descend",
    title: "Par l’Étoile lorsqu’elle descend",
    subtitle: "Exégèse de la sourate l'Etoile",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/par-letoile-lorsquelle-descend.jpg", alt: "Couverture — Par l’Étoile lorsqu’elle descend", width: 600, height: 980 },
    priceLabel: "12,00 € (papier) – 8,00 € (ebook)",
    isbn: "978-2-930978-16-1",
    purchaseUrl: "https://les7lectures.com/par-letoile-lorsquelle-descend/",
  },
  {
    slug: "nour-al-hikam-lumiere-des-sagesses",
    title: "Nour al-Hikam Lumière des Sagesses",
    subtitle: "La Voie Blanche - Chapitre V",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/nour-al-hikam-lumiere-des-sagesses.jpg", alt: "Couverture — Nour al-Hikam Lumière des Sagesses", width: 600, height: 980 },
    priceLabel: "8,00 € (papier) – 5,00 € (ebook)",
    isbn: "978-2-930978-29-1",
    purchaseUrl: "https://les7lectures.com/nour-al-hikam-lumiere-des-sagesses/",
  },
  {
    slug: "la-voie-du-vrai",
    title: "La Voie du Vrai",
    subtitle: "Exégèse ésotérique",
    author: "Louis Mazué",
    description: null,
    cover: { src: "/images/livres/la-voie-du-vrai.jpg", alt: "Couverture — La Voie du Vrai", width: 600, height: 980 },
    priceLabel: "11,00 € (papier) – 8,00 € (ebook)",
    isbn: "978-2-930978-31-4",
    purchaseUrl: "https://les7lectures.com/la-voie-du-vrai/",
  },
  {
    slug: "nour-al-quran-lumiere-du-coran",
    title: "Nour al-Quran Lumière du Coran",
    subtitle: "La Voie Blanche - Chapitre III",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/nour-al-quran-lumiere-du-coran.jpg", alt: "Couverture — Nour al-Quran Lumière du Coran", width: 600, height: 980 },
    priceLabel: "9,00 € (papier) – 5,00 € (ebook)",
    isbn: "978-2-930978-30-7",
    purchaseUrl: "https://les7lectures.com/nour-al-quran-lumiere-du-coran/",
  },
  {
    slug: "verset-de-louverture-spirituelle",
    title: "Verset de l’ouverture spirituelle",
    subtitle: "La Voie Blanche - Chapitre II",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/verset-de-louverture-spirituelle.jpg", alt: "Couverture — Verset de l’ouverture spirituelle", width: 600, height: 980 },
    priceLabel: "8,00 € (papier) – 5,00 € (ebook)",
    isbn: "978-2-930978-28-4",
    purchaseUrl: "https://les7lectures.com/verset-de-louverture-spirituelle/",
  },
  {
    slug: "la-voie-blanche",
    title: "La Voie Blanche (cartonné)",
    subtitle: "al-Mahajjat al-Bayda",
    author: "Mohamed Faouzi Al Karkari",
    description: null,
    cover: { src: "/images/livres/la-voie-blanche.jpg", alt: "Couverture — La Voie Blanche (cartonné)", width: 600, height: 980 },
    priceLabel: "36,00 €",
    isbn: "978-2-930978-20-8",
    purchaseUrl: "https://les7lectures.com/la-voie-blanche/",
  },
];

/** Ouvrages mis en avant sur la page d'accueil (dans cet ordre). */
export const featuredBooks = ["les-fondements-de-la-tariqa-karkariya", "la-voie-blanche", "le-livre-du-secret", "le-vetement-rapiece", "epitre-lunaire", "zamzam-de-la-connaissance", "les-ascensions-lumineuses"]
  .map((slug) => books.find((b) => b.slug === slug))
  .filter((b): b is Book => Boolean(b));

export const bookstore = {
  eyebrow: "Ouvrages",
  title: "Des livres pour prolonger la rencontre",
  text: "Transmettre, c’est aussi écrire, lire et partager. Les ouvrages du Shaykh Mohamed Faouzi Al Karkari et de ses disciples, publiés par les éditions Les 7 Lectures.",
  publisher: { name: "Les 7 Lectures", url: "https://les7lectures.com/" },
  cta: { label: "Découvrir les ouvrages", href: "/librairie" },
};
